spring.application.name=employee-management-portal
spring.datasource.url=jdbc:mysql://localhost:3306/employee_management_portal?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

#jwt.secret=ThisIsMyVerySecureSecretKeyForEmployeeManagementPortal2026Laneway[we're gonna replace it later to environment variables for production]
#for this project lets take properly generated Base-64 encoded key
jwt.secret = ZmY5OGQ5NDY2ZGE2NjMwYjFkMTNkNjYxM2I0Y2VmZTVlNzYxZmIxNDMwNTUwYmQ4NzZmZTU2NjQ3Y2RmODQ3Yg==
jwt.expiration=86400000